site_name: Virtual Secretary Documentation

repo_url: https://github.com/aurelienpierreeng/VirtualSecretary
repo_name: aurelienpierreeng/VirtualSecretary

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.sections
  palette:
    primary: pink
  logo: assets/virtualsecretary-inverted.png


markdown_extensions:
  - attr_list
  - md_in_html
  - smarty
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: "¤"
  - admonition
  - callouts:
      strip_period: no
  - footnotes
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
- search
- autorefs
- offline
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    custom_templates: templates
    default_handler: python
    enable_inventory: true
    handlers:
      python:
        paths: [src]
        import:
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/1.24/objects.inv
        - https://www.nltk.org/objects.inv
        - https://radimrehurek.com/gensim/objects.inv
        options:
          show_root_heading: true
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: yes
          show_signature: yes
          show_signature_annotations: yes
          show_if_no_docstring: no
          separate_signature: yes
          docstring_section_style: table
          show_source: yes
          show_category_heading: no
          show_submodules: yes
          members_order: alphabetical
          heading_level: 3
